### ISSUE TITLE
error on every run

### ISSUE THREAD

**Issue by iantor** [codecoll/feedly#1]
Just tried this out.  I'm a heavy user of Feedly, have hundreds of feeds.  Here's the record from the *Messages* buffer:

Getting user id...
Contacting host: cloud.feedly.com:443
gnutls.c: [1] (Emacs) connecting to host: cloud.feedly.com
gnutls.c: [1] (Emacs) allocating credentials
gnutls.c: [2] (Emacs) allocating x509 credentials
gnutls.c: [2] (Emacs) using default verification flags
gnutls.c: [audit] There was a non-CA certificate in the trusted list: CN=localhost.

gnutls.c: [audit] There was a non-CA certificate in the trusted list: OU=Copyright (c) 1997 Microsoft Corp.,OU=Microsoft Corporation,CN=Microsoft Root Authority.

gnutls.c: [audit] There was a non-CA certificate in the trusted list: C=US,O=MSFT,CN=Microsoft Authenticode(tm) Root Authority.

gnutls.c: [audit] There was a non-CA certificate in the trusted list: CN=Root Agency.

gnutls.c: [1] (Emacs) gnutls callbacks
gnutls.c: [1] (Emacs) gnutls_init
gnutls.c: [1] (Emacs) got non-default priority string: NORMAL:%DUMBFW
gnutls.c: [1] (Emacs) setting the priority string
gnutls.c: [2] added 53 ciphersuites, 14 sig algos and 8 groups into priority list

gnutls.c: [2] Keeping ciphersuite c0.2c (GNUTLS_ECDHE_ECDSA_AES_256_GCM_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.87 (GNUTLS_ECDHE_ECDSA_CAMELLIA_256_GCM_SHA384)

gnutls.c: [2] Keeping ciphersuite cc.a9 (GNUTLS_ECDHE_ECDSA_CHACHA20_POLY1305)

gnutls.c: [2] Keeping ciphersuite c0.ad (GNUTLS_ECDHE_ECDSA_AES_256_CCM)

gnutls.c: [2] Keeping ciphersuite c0.0a (GNUTLS_ECDHE_ECDSA_AES_256_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite c0.24 (GNUTLS_ECDHE_ECDSA_AES_256_CBC_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.73 (GNUTLS_ECDHE_ECDSA_CAMELLIA_256_CBC_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.2b (GNUTLS_ECDHE_ECDSA_AES_128_GCM_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.86 (GNUTLS_ECDHE_ECDSA_CAMELLIA_128_GCM_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.ac (GNUTLS_ECDHE_ECDSA_AES_128_CCM)

gnutls.c: [2] Keeping ciphersuite c0.09 (GNUTLS_ECDHE_ECDSA_AES_128_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite c0.23 (GNUTLS_ECDHE_ECDSA_AES_128_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.72 (GNUTLS_ECDHE_ECDSA_CAMELLIA_128_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.30 (GNUTLS_ECDHE_RSA_AES_256_GCM_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.8b (GNUTLS_ECDHE_RSA_CAMELLIA_256_GCM_SHA384)

gnutls.c: [2] Keeping ciphersuite cc.a8 (GNUTLS_ECDHE_RSA_CHACHA20_POLY1305)

gnutls.c: [2] Keeping ciphersuite c0.14 (GNUTLS_ECDHE_RSA_AES_256_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite c0.28 (GNUTLS_ECDHE_RSA_AES_256_CBC_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.77 (GNUTLS_ECDHE_RSA_CAMELLIA_256_CBC_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.2f (GNUTLS_ECDHE_RSA_AES_128_GCM_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.8a (GNUTLS_ECDHE_RSA_CAMELLIA_128_GCM_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.13 (GNUTLS_ECDHE_RSA_AES_128_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite c0.27 (GNUTLS_ECDHE_RSA_AES_128_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.76 (GNUTLS_ECDHE_RSA_CAMELLIA_128_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite 00.9d (GNUTLS_RSA_AES_256_GCM_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.7b (GNUTLS_RSA_CAMELLIA_256_GCM_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.9d (GNUTLS_RSA_AES_256_CCM)

gnutls.c: [2] Keeping ciphersuite 00.35 (GNUTLS_RSA_AES_256_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite 00.3d (GNUTLS_RSA_AES_256_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite 00.84 (GNUTLS_RSA_CAMELLIA_256_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite 00.c0 (GNUTLS_RSA_CAMELLIA_256_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite 00.9c (GNUTLS_RSA_AES_128_GCM_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.7a (GNUTLS_RSA_CAMELLIA_128_GCM_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.9c (GNUTLS_RSA_AES_128_CCM)

gnutls.c: [2] Keeping ciphersuite 00.2f (GNUTLS_RSA_AES_128_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite 00.3c (GNUTLS_RSA_AES_128_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite 00.41 (GNUTLS_RSA_CAMELLIA_128_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite 00.ba (GNUTLS_RSA_CAMELLIA_128_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite 00.9f (GNUTLS_DHE_RSA_AES_256_GCM_SHA384)

gnutls.c: [2] Keeping ciphersuite c0.7d (GNUTLS_DHE_RSA_CAMELLIA_256_GCM_SHA384)

gnutls.c: [2] Keeping ciphersuite cc.aa (GNUTLS_DHE_RSA_CHACHA20_POLY1305)

gnutls.c: [2] Keeping ciphersuite c0.9f (GNUTLS_DHE_RSA_AES_256_CCM)

gnutls.c: [2] Keeping ciphersuite 00.39 (GNUTLS_DHE_RSA_AES_256_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite 00.6b (GNUTLS_DHE_RSA_AES_256_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite 00.88 (GNUTLS_DHE_RSA_CAMELLIA_256_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite 00.c4 (GNUTLS_DHE_RSA_CAMELLIA_256_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite 00.9e (GNUTLS_DHE_RSA_AES_128_GCM_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.7c (GNUTLS_DHE_RSA_CAMELLIA_128_GCM_SHA256)

gnutls.c: [2] Keeping ciphersuite c0.9e (GNUTLS_DHE_RSA_AES_128_CCM)

gnutls.c: [2] Keeping ciphersuite 00.33 (GNUTLS_DHE_RSA_AES_128_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite 00.67 (GNUTLS_DHE_RSA_AES_128_CBC_SHA256)

gnutls.c: [2] Keeping ciphersuite 00.45 (GNUTLS_DHE_RSA_CAMELLIA_128_CBC_SHA1)

gnutls.c: [2] Keeping ciphersuite 00.be (GNUTLS_DHE_RSA_CAMELLIA_128_CBC_SHA256)

gnutls.c: [2] HSK[00b07db0]: sent server name: 'cloud.feedly.com'

gnutls.c: [2] WRITE: -1 returned from 0f58d800, errno: 11

gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again.
gnutls.c: [2] WRITE: -1 returned from 0f58d800, errno: 11

gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again. [3 times]
gnutls.c: [2] received curve X25519

gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again.

nil

Fetching new items... 
gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again. [55 times]

"1714cade932:c8411:717844b4"

Fetching new items... 1000
gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again. [85 times]

"17111efb36f:4ce6eb:f050c342"

error in process filter: feedly-fetch-batch-of-new-items: end
error in process filter: end

**Comment by codecoll** [comment]
I had suddenly unexpected network errors earlier too, but it went away for me, so I guess it was a feedly server error, because I have no errors currently. I just use the standard url-retrieve function of emacs, so I don't do anything special networkwise.

**Comment by codecoll** [comment]
No response in a week. Assuming the problem resolved. Closing.
